import { useMemo, useState } from "react";
import {
  Bot, ChevronLeft, Code2, FolderGit2, GitPullRequest, LayoutDashboard,
  ListTodo, ShieldCheck, Users, BookOpen, Rocket, Search, Plus, Bell,
  Menu, X, LogOut, CheckCircle2, Circle, Bug, Map, FileText, Lock,
  Sparkles, Play, Send, Trash2, Save, GitBranch, Eye, EyeOff
} from "lucide-react";

type Page = "dashboard" | "projects" | "ai" | "teams" | "security" | "profile";
type Tab = "Code" | "Tasks" | "Issues" | "Pull Requests" | "Roadmap" | "Team" | "Documentation" | "Releases" | "Deploy";
type Task = { id:number; title:string; done:boolean; priority:"منخفض"|"متوسط"|"عالي" };
type Issue = { id:number; title:string; status:"مفتوحة"|"مغلقة"; severity:"منخفض"|"متوسط"|"عالي" };
type Project = { id:number; name:string; description:string; tech:string[]; private:boolean };

const nav = [
  {id:"dashboard", label:"لوحة القيادة", icon:LayoutDashboard},
  {id:"projects", label:"المشاريع", icon:FolderGit2},
  {id:"ai", label:"AI Assistant", icon:Bot},
  {id:"teams", label:"الفرق", icon:Users},
  {id:"security", label:"Deploy & Security", icon:ShieldCheck},
  {id:"profile", label:"الملف الشخصي", icon:Users},
] as const;

const initialProjects:Project[] = [
  {id:1,name:"My Project",description:"تطبيق ويب متكامل",tech:["TypeScript","React","Firebase"],private:true},
  {id:2,name:"DevForge Web",description:"منصة المطورين",tech:["React","Node.js"],private:false},
  {id:3,name:"Security Lab",description:"مختبر أمني مصرح به",tech:["Python","Security"],private:true},
];
const initialTasks:Task[]=[
  {id:1,title:"إضافة تسجيل الدخول",done:true,priority:"عالي"},
  {id:2,title:"تحسين محرر الكود",done:false,priority:"متوسط"},
  {id:3,title:"كتابة اختبارات الواجهة",done:false,priority:"متوسط"},
];
const initialIssues:Issue[]=[
  {id:1,title:"زر الحفظ لا يظهر على الهاتف",status:"مفتوحة",severity:"متوسط"},
  {id:2,title:"تحسين تحميل قائمة الملفات",status:"مفتوحة",severity:"منخفض"},
];

function App(){
  const [logged,setLogged]=useState(()=>localStorage.getItem("devforge-auth")==="1");
  const [page,setPage]=useState<Page>("dashboard");
  const [mobileOpen,setMobileOpen]=useState(false);
  const [workspace,setWorkspace]=useState<Project|null>(null);
  const [projects,setProjects]=useState<Project[]>(initialProjects);
  const [tasks,setTasks]=useState<Task[]>(initialTasks);
  const [issues,setIssues]=useState<Issue[]>(initialIssues);
  const [notice,setNotice]=useState("");
  const notify=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2200)};
  if(!logged) return <Login onLogin={()=>{localStorage.setItem("devforge-auth","1");setLogged(true)}}/>;
  const openProject=(p?:Project)=>setWorkspace(p||projects[0]);
  const createProject=()=>{const name=prompt("اسم المشروع؟")?.trim();if(!name)return;const p={id:Date.now(),name,description:"مشروع جديد",tech:["TypeScript","React"],private:true};setProjects(x=>[...x,p]);notify("تم إنشاء المشروع");setWorkspace(p)};
  return <div className="app">
    <aside className={mobileOpen?"sidebar open":"sidebar"}>
      <div className="brand"><div className="logo">D</div><div><b>DevForge</b><small>Developer Platform</small></div></div>
      <nav>{nav.map(({id,label,icon:Icon})=><button key={id} className={page===id?"nav active":"nav"} onClick={()=>{setPage(id);setMobileOpen(false)}}><Icon size={19}/><span>{label}</span></button>)}</nav>
      <div className="sideProject"><span>المشروع الحالي</span><b>{workspace?.name||projects[0].name}</b><button onClick={()=>openProject(workspace||projects[0])}>فتح مساحة المشروع <ChevronLeft size={16}/></button></div>
    </aside>
    {mobileOpen&&<button className="backdrop" onClick={()=>setMobileOpen(false)} aria-label="إغلاق"/>}
    <main className="main">
      <header className="topbar"><button className="iconBtn mobileMenu" onClick={()=>setMobileOpen(true)}><Menu/></button><div className="crumb">{pageTitle(page)}</div><div className="topActions"><button className="iconBtn" onClick={()=>notify("البحث داخل المشروع جاهز")}> <Search size={19}/></button><button className="iconBtn" onClick={()=>notify("لا توجد إشعارات جديدة")}> <Bell size={19}/></button><button className="avatar">DF</button></div></header>
      <section className="content">
        {page==="dashboard"&&<Dashboard projects={projects} tasks={tasks} issues={issues} onOpenProject={()=>openProject()} onNew={createProject}/>} 
        {page==="projects"&&<Projects projects={projects} onOpen={openProject} onNew={createProject} onDelete={(id)=>setProjects(x=>x.filter(p=>p.id!==id))}/>} 
        {page==="ai"&&<AI projects={projects} tasks={tasks} issues={issues}/>} 
        {page==="teams"&&<Teams/>}
        {page==="security"&&<Security/>}
        {page==="profile"&&<Profile onLogout={()=>{localStorage.removeItem("devforge-auth");setLogged(false)}}/>}
      </section>
    </main>
    {workspace&&<ProjectWorkspace project={workspace} onClose={()=>setWorkspace(null)} tasks={tasks} setTasks={setTasks} issues={issues} setIssues={setIssues} notify={notify}/>} 
    {notice&&<div className="toast"><CheckCircle2 size={18}/>{notice}</div>}
  </div>
}
function pageTitle(page:Page){return nav.find(n=>n.id===page)?.label||"DevForge"}
function Login({onLogin}:{onLogin:()=>void}){const [email,setEmail]=useState("");const [pass,setPass]=useState("");const [show,setShow]=useState(false);return <div className="login"><div className="loginCard"><div className="logo big">D</div><h1>DevForge</h1><p>منصة إدارة المشاريع البرمجية</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني" type="email"/><div className="passInput"><input value={pass} onChange={e=>setPass(e.target.value)} placeholder="كلمة المرور" type={show?"text":"password"}/><button onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><button className="primary full" onClick={onLogin} disabled={!email||!pass}><Lock size={17}/> دخول إلى DevForge</button><small>وضع تجريبي محلي — بياناتك لا تُرسل لأي خادم.</small></div></div>}
function Dashboard({projects,tasks,issues,onOpenProject,onNew}:{projects:Project[];tasks:Task[];issues:Issue[];onOpenProject:()=>void;onNew:()=>void}){return <div className="stack"><div className="hero"><div><span className="eyebrow">DEVFORGE</span><h1>مساحة عمل المطورين</h1><p>الكود والمشاريع والتعاون والذكاء الاصطناعي في مكان واحد.</p></div><div className="heroActions"><button className="primary" onClick={onOpenProject}><FolderGit2 size={18}/> فتح المشروع</button><button className="secondary" onClick={onNew}><Plus size={18}/> مشروع جديد</button></div></div><div className="stats"><Stat n={String(projects.length)} t="المشاريع"/><Stat n={String(tasks.filter(x=>!x.done).length)} t="المهام المفتوحة"/><Stat n="3" t="Pull Requests"/><Stat n={String(issues.filter(x=>x.status==="مفتوحة"&&x.severity==="عالي").length)} t="مشاكل حرجة"/></div><div className="grid2"><Card title="النشاط الأخير"><Activity text="تم تحديث ملف README.md" time="منذ 12 دقيقة"/><Activity text="تم إنشاء مهمة جديدة" time="منذ 35 دقيقة"/><Activity text="تم فتح Pull Request" time="منذ ساعة"/></Card><Card title="المشروع الحالي"><div className="projectSummary"><div className="projectIcon"><Code2/></div><div><b>{projects[0]?.name}</b><p>{projects[0]?.description}</p></div></div><button className="secondary full" onClick={onOpenProject}>فتح مساحة المشروع</button></Card></div></div>}
function Stat({n,t}:{n:string;t:string}){return <div className="stat"><b>{n}</b><span>{t}</span></div>}
function Activity({text,time}:{text:string;time:string}){return <div className="activity"><span className="dot"/><div><b>{text}</b><small>{time}</small></div></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="card"><div className="cardHead"><h3>{title}</h3></div>{children}</div>}
function Projects({projects,onOpen,onNew,onDelete}:{projects:Project[];onOpen:(p:Project)=>void;onNew:()=>void;onDelete:(id:number)=>void}){return <div className="stack"><div className="sectionHead"><div><h2>المشاريع</h2><p>أنشئ مشاريعك وافتح مساحة العمل الكاملة.</p></div><button className="primary" onClick={onNew}><Plus size={18}/> مشروع جديد</button></div><div className="projectGrid">{projects.map(p=><div className="card projectCard" key={p.id}><div className="projectTop"><div className="projectIcon"><Code2/></div><button className="dangerBtn" onClick={()=>onDelete(p.id)} title="حذف"><Trash2 size={16}/></button></div><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tech.map(t=><span key={t}>{t}</span>)}</div><div className="projectMeta"><span>{p.private?"خاص":"عام"}</span><GitBranch size={14}/><span>main</span></div><button className="secondary full" onClick={()=>onOpen(p)}>فتح المشروع</button></div>)}</div></div>}
function AI({projects,tasks,issues}:{projects:Project[];tasks:Task[];issues:Issue[]}){const [msg,setMsg]=useState("");const [messages,setMessages]=useState<{role:string;text:string}[]>([]);const suggestions=["حلل حالة المشروع","اكتب خطة لإضافة تسجيل الدخول","راجع المشاكل المفتوحة","أنشئ اختبارات للكود"];const reply=(q:string)=>{const l=q.toLowerCase();let r="سأحلل الطلب ضمن سياق DevForge وأقترح خطوات قبل أي تغيير مهم.";if(l.includes("حالة")||l.includes("المشروع"))r=`حالة المشروع: ${projects.length} مشاريع، ${tasks.filter(x=>!x.done).length} مهام مفتوحة، و${issues.filter(x=>x.status==="مفتوحة").length} مشاكل مفتوحة. أقترح البدء بالمهام ذات الأولوية العالية.`;else if(l.includes("تسجيل")||l.includes("دخول"))r="خطة آمنة: 1) إضافة شاشة تسجيل الدخول 2) ربط مزود المصادقة 3) حماية المسارات 4) حفظ جلسة المستخدم 5) اختبار الدخول والخروج. لن يتم حذف بيانات موجودة.";else if(l.includes("اختبار"))r="يمكن إنشاء اختبارات للوحدات والواجهات، ثم تشغيلها قبل الدمج. ابدأ بالمكونات الحساسة ومسارات تسجيل الدخول.";else if(l.includes("مشاكل")||l.includes("bug"))r=`لديك ${issues.filter(x=>x.status==="مفتوحة").length} مشاكل مفتوحة. راجع أولاً المشكلة ذات الخطورة الأعلى ثم أضف خطوات إعادة الإنتاج والحل المقترح.`;setMessages(m=>[...m,{role:"user",text:q},{role:"ai",text:r}]);setMsg("")};return <div className="stack"><div><h2>AI Assistant</h2><p>مساعد محلي أولي يفهم بيانات مساحة العمل. يمكن ربطه لاحقًا بنموذج حقيقي.</p></div><div className="aiBox"><div className="messages">{messages.length===0&&<div className="empty"><Bot size={42}/><h3>كيف أساعدك؟</h3><p>اسأل عن المشروع، الأخطاء، الاختبارات أو خطة ميزة.</p><div className="suggestions">{suggestions.map(s=><button className="secondary" key={s} onClick={()=>reply(s)}><Sparkles size={15}/>{s}</button>)}</div></div>}{messages.map((m,i)=><div className={m.role==="user"?"userMsg":"aiMsg"} key={i}>{m.text}</div>)}</div><div className="composer"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&reply(msg)} placeholder="اكتب طلبك..."/><button className="primary" onClick={()=>reply(msg)}><Send size={16}/> إرسال</button></div></div></div>}
function Teams(){return <div className="stack"><div><h2>الفرق</h2><p>أعضاء المشروع والصلاحيات.</p></div><div className="teamGrid"><Card title="الأعضاء"><Activity text="أنت — Owner" time="صلاحية كاملة"/><Activity text="Developer — Member" time="صلاحية تطوير"/><Activity text="Reviewer — Member" time="مراجعة Pull Requests"/></Card><Card title="الدعوات"><p>لا توجد دعوات معلقة.</p><button className="secondary" onClick={()=>alert("في النسخة المتصلة سيتم إرسال دعوة بالبريد")}>دعوة عضو</button></Card></div></div>}
function Security(){const [running,setRunning]=useState(false);const [done,setDone]=useState(false);const run=()=>{setRunning(true);setDone(false);setTimeout(()=>{setRunning(false);setDone(true)},1300)};return <div className="stack"><div><h2>Deploy & Security</h2><p>فحوصات محلية قبل النشر.</p></div><div className="stats"><Stat n="0" t="ثغرات حرجة"/><Stat n="3" t="تنبيهات"/><Stat n="100%" t="HTTPS"/><Stat n="جاهز" t="حالة النشر"/></div><Card title="فحص المشروع"><Activity text="حماية الأسرار" time="تأكد من استخدام متغيرات البيئة"/><Activity text="صلاحيات قاعدة البيانات" time="استخدم قواعد وصول دقيقة"/><Activity text="اعتمادات الحزم" time="حدّث الحزم بانتظام"/><button className="primary" onClick={run} disabled={running}><Play size={16}/>{running?"جارٍ الفحص...":"تشغيل فحص الأمان"}</button>{done&&<div className="successBox"><CheckCircle2 size={18}/> اكتمل الفحص: لم يتم العثور على مشكلة حرجة في هذا الفحص المحلي.</div>}</Card></div>}
function Profile({onLogout}:{onLogout:()=>void}){return <div className="stack"><div><h2>الملف الشخصي</h2><p>إعدادات حساب المطور.</p></div><div className="card profile"><div className="bigAvatar">DF</div><h3>DevForge Developer</h3><p>@developer</p><div className="tags"><span>TypeScript</span><span>React</span><span>Firebase</span><span>Security</span></div><button className="secondary" onClick={onLogout}><LogOut size={16}/> تسجيل الخروج</button></div></div>}
function ProjectWorkspace({project,onClose,tasks,setTasks,issues,setIssues,notify}:{project:Project;onClose:()=>void;tasks:Task[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>;issues:Issue[];setIssues:React.Dispatch<React.SetStateAction<Issue[]>>;notify:(s:string)=>void}){const [tab,setTab]=useState<Tab>("Code");const tabs:[[Tab,any],...any]=[["Code",Code2],["Tasks",ListTodo],["Issues",Bug],["Pull Requests",GitPullRequest],["Roadmap",Map],["Team",Users],["Documentation",BookOpen],["Releases",Rocket],["Deploy",ShieldCheck]];return <div className="modal"><div className="workspace"><header className="workspaceHead"><div><b>{project.name}</b><small> · main · {project.private?"private":"public"}</small></div><button className="iconBtn" onClick={onClose}><X/></button></header><div className="tabs">{tabs.map(([name,Icon])=><button className={tab===name?"tab active":"tab"} onClick={()=>setTab(name)} key={name}><Icon size={16}/>{name}</button>)}</div><div className="workspaceBody">{tab==="Code"?<CodePanel notify={notify}/>:tab==="Tasks"?<TasksPanel tasks={tasks} setTasks={setTasks}/>:tab==="Issues"?<IssuesPanel issues={issues} setIssues={setIssues}/>:tab==="Pull Requests"?<PRPanel notify={notify}/>:tab==="Roadmap"?<Roadmap/>:tab==="Team"?<WorkspaceTeam/>:tab==="Documentation"?<Docs/>:tab==="Releases"?<Releases notify={notify}/>:<DeployPanel notify={notify}/>}</div></div></div>}
function CodePanel({notify}:{notify:(s:string)=>void}){const files=["src/","  App.tsx","  main.tsx","  styles.css","  firebase.ts","README.md","package.json",".env.example"];const [selected,setSelected]=useState("App.tsx");const [code,setCode]=useState("function DevForge() {\n  return (\n    <DeveloperPlatform />\n  );\n}");const save=()=>{localStorage.setItem("devforge-code-"+selected,code);notify("تم حفظ الملف محليًا")};return <div className="codeLayout"><aside className="tree"><b>FILES</b>{files.map(f=><div key={f} className={selected===f.trim()?"selected":""} onClick={()=>!f.endsWith("/")&&setSelected(f.trim())}>{f}</div>)}<button className="secondary full" onClick={()=>notify("في النسخة المتصلة يمكنك إنشاء ملف جديد")}>+ ملف</button></aside><div className="editor"><div className="editorHead">{selected}<span>main</span></div><textarea value={code} onChange={e=>setCode(e.target.value)} spellCheck={false}/><div className="editorBar"><button className="primary" onClick={save}><Save size={16}/> حفظ</button><span>TypeScript · UTF-8</span></div></div></div>}
function TasksPanel({tasks,setTasks}:{tasks:Task[];setTasks:React.Dispatch<React.SetStateAction<Task[]>>}){const add=()=>{const title=prompt("اسم المهمة؟")?.trim();if(title)setTasks(x=>[...x,{id:Date.now(),title,done:false,priority:"متوسط"}])};return <div className="panel"><div className="sectionHead"><div><h3>المهام</h3><p>{tasks.filter(x=>!x.done).length} مفتوحة</p></div><button className="primary" onClick={add}><Plus size={16}/> مهمة جديدة</button></div>{tasks.map(t=><div className="rowItem" key={t.id} onClick={()=>setTasks(x=>x.map(a=>a.id===t.id?{...a,done:!a.done}:a))}><span>{t.done?<CheckCircle2 size={20}/>:<Circle size={20}/>}</span><div className={t.done?"done":""}><b>{t.title}</b><small>الأولوية: {t.priority}</small></div></div>)}</div>}
function IssuesPanel({issues,setIssues}:{issues:Issue[];setIssues:React.Dispatch<React.SetStateAction<Issue[]>>}){const add=()=>{const title=prompt("وصف المشكلة؟")?.trim();if(title)setIssues(x=>[...x,{id:Date.now(),title,status:"مفتوحة",severity:"متوسط"}])};return <div className="panel"><div className="sectionHead"><div><h3>Issues</h3><p>تتبع الأخطاء والمشاكل.</p></div><button className="primary" onClick={add}><Plus size={16}/> Issue جديدة</button></div>{issues.map(i=><div className="rowItem" key={i.id}><Bug size={19}/><div><b>{i.title}</b><small>{i.status} · خطورة {i.severity}</small></div><button className="secondary" onClick={()=>setIssues(x=>x.map(a=>a.id===i.id?{...a,status:a.status==="مفتوحة"?"مغلقة":"مفتوحة"}:a))}>{i.status==="مفتوحة"?"إغلاق":"فتح"}</button></div>)}</div>}
function PRPanel({notify}:{notify:(s:string)=>void}){return <div className="panel"><div className="sectionHead"><div><h3>Pull Requests</h3><p>مراجعة تغييرات الكود قبل الدمج.</p></div><button className="primary" onClick={()=>notify("تم إنشاء Pull Request تجريبي")}> <Plus size={16}/> PR جديد</button></div><div className="pr"><GitPullRequest/><div><b>feat: improve project workspace</b><small>#12 · مفتوح · يحتاج مراجعة</small></div><span className="pill">2 ملفات</span></div><div className="pr"><GitPullRequest/><div><b>fix: mobile navigation</b><small>#11 · مدمج</small></div><span className="pill">✓ merged</span></div></div>}
function Roadmap(){return <div className="panel"><h3>Roadmap</h3><div className="roadmap"><div><span className="phase donePhase"/> <b>الأساس</b><small>Dashboard · Projects · Auth</small></div><div><span className="phase activePhase"/> <b>التعاون</b><small>Tasks · Issues · Pull Requests</small></div><div><span className="phase"/> <b>الذكاء الاصطناعي</b><small>تحليل المشروع وربط نموذج حقيقي</small></div><div><span className="phase"/> <b>النشر</b><small>CI/CD · Domains · Monitoring</small></div></div></div>}
function WorkspaceTeam(){return <div className="panel"><h3>Team</h3><div className="member"><div className="miniAvatar">DF</div><div><b>DevForge Developer</b><small>Owner</small></div></div><div className="member"><div className="miniAvatar">DV</div><div><b>Developer</b><small>Member</small></div></div></div>}
function Docs(){const [text,setText]=useState("# My Project\n\n## الهدف\nاكتب هنا وصف المشروع وطريقة تشغيله.\n\n## التطوير\nnpm install\nnpm run dev\n\n## المساهمة\nافتح Issue ثم Pull Request.");return <div className="docs"><div className="docSide"><FileText/><b>README.md</b><span>CONTRIBUTING.md</span><span>ARCHITECTURE.md</span></div><textarea value={text} onChange={e=>setText(e.target.value)}/></div>}
function Releases({notify}:{notify:(s:string)=>void}){return <div className="panel"><div className="sectionHead"><div><h3>Releases</h3><p>إصدارات المشروع.</p></div><button className="primary" onClick={()=>notify("تم إنشاء إصدار v0.1.0 محليًا")}> <Rocket size={16}/> إصدار جديد</button></div><div className="release"><b>v0.1.0</b><span>Latest</span><small>أول إصدار من DevForge · main</small></div></div>}
function DeployPanel({notify}:{notify:(s:string)=>void}){return <div className="panel"><h3>Deploy</h3><p>جهّز المشروع للنشر بدون وضع الأسرار داخل الكود.</p><div className="deployGrid"><div><CheckCircle2/><b>Build</b><small>جاهز</small></div><div><ShieldCheck/><b>Security</b><small>قواعد أساسية</small></div><div><Rocket/><b>Hosting</b><small>اختر مزود الاستضافة</small></div></div><button className="primary" onClick={()=>notify("تم تجهيز Checklist للنشر")}>تجهيز للنشر</button></div>}
export default App;
